Show application name.

diff --git a/docker/Dockerfile_base b/docker/Dockerfile_base
--- a/docker/Dockerfile_base
+++ b/docker/Dockerfile_base
@@ -15,7 +15,7 @@ ENV APP_HOME=./
 COPY . .
 RUN rm **/*.log | true
 
-RUN gem install bundler -v 2.1.4
+RUN gem install bundler
 
 ENV PASSENGER=true
 ENV PUMA=true
@@ -34,6 +34,11 @@ ENV APP_LOG=/tmp/agent/app.log
 
 RUN bundle exec rake app:assets:precompile
 RUN bundle exec rails db:migrate
+
+# Just in case, clean up local.
+RUN rm ./contrast_security.yaml ./spec/dummy/contrast_security.yaml || true
+RUN rm ./*log ./spec/dummy/*log || true
+RUN rm ./agent || true
 
 RUN touch /tmp/tail_me
 
